name: Release

permissions:
    contents: write

on:
    push:
        tags:
            - v[0-9]+.*

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/create-gh-release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

    upload-assets:
        needs: create-release
        strategy:
            matrix:
                include:
                    - target: i686-unknown-linux-gnu
                      os: ubuntu-20.04
                      artifact_name: libauxmos
                    - target: i686-pc-windows-msvc
                      os: windows-latest
                      artifact_name: auxmos
                      debug_pdb_name: auxmos.pdb
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install g++ multilib
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install build-essential g++-multilib libc6-i386 libstdc++6:i386
              if: matrix.os == 'ubuntu-20.04'
            - uses: actions/checkout@v4
            - uses: taiki-e/upload-rust-binary-action@v1
              with:
                  bin: ${{ matrix.artifact_name }}
                  target: ${{ matrix.target }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checksum: sha256
                  features: katmos
                  tar: none
                  zip: none
                  asset: ${{ matrix.debug_pdb_name }}
